server:
    port: 8080
spring:
    profiles:
        include: uat
    application:
        name: Chat

#logging:
#    level:
#        com.zaxxer.hikari: DEBUG
# MyBatis Plus 的配置
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mybatis 配置文件的路径
    # config-location: "classpath:mybatis/mybatis.config"