server:
    port: 8080

spring:
    application:
        name: Chat
    datasource:
        url: jdbc:mysql://114.55.235.0:3306/CHAT
        username: root
        password: 1234
        type: com.alibaba.druid.pool.DruidDataSource  # 指定 Druid 作为数据源
        driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#    level:
#        com.zaxxer.hikari: DEBUG
# MyBatis Plus 的配置
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mybatis 配置文件的路径
    # config-location: "classpath:mybatis/mybatis.config"